### ISSUE TITLE
Download link Spoofax is broken

### ISSUE THREAD

**Issue by AlexanderGrooff** [TUDelft-IN4303-2014/assignments#35]
The Spoofax download link in Milestone 1: Syntax Analysis originally points to http://metaborg.org/wiki/spoofax/download, but this should be http://metaborg.org/download/.

**Comment by guwac** [comment]
Please note that this repository keeps the assignment descriptions for 2014. You can find the assignments for 2015 here: http://tudelft-in4303.github.io/assignments/
